### ISSUE TITLE
Need e10s support

### ISSUE THREAD

**Issue by streetwolf** [schomery/easy-screenshot#1]
Under e10s no screenshot is taken.  Can you please add e10 support and also have your add-on signed which I think Mozilla does for you but I don't know if there are any criteria your add-on needs.

**Comment by inbasic** [comment]
Thanks for the report. The issue is now fixed on the developer version,
https://github.com/schomery/easy-screenshot/blob/master/src.safariextension/executables/extension.xpi?raw=true

Download this XPI file and drop it in Firefox. Let me know if there is any problem with e10s

**Comment by streetwolf** [comment]
Looking good.  Thanks.

----- Original Message -----
