### ISSUE TITLE
"Capture a Portion" feature causes all future HTTP Requests to timeout

### ISSUE THREAD

**Issue by badaczewski** [schomery/easy-screenshot#13]
After using the "Capture a Portion" feature from Google Chrome Version 99.0.4844.82 (Official Build) (64-bit) as well as previous versions, the browsers lose the ability to make new HTTP requests, pages just spin and never load.

The screenshot is successfully generated, but then the browser windows are unusable until I close all instances of Chrome  and restart.

**Comment by schomery** [comment]
I am not able to reproduce this. Can you confirm the issue on a new profile?

**Comment by badaczewski** [comment]
Sorry, you are correct. This appears to be something unique to my profile. I'll try to figure out what I have enabled causing the issue.
