### ISSUE TITLE
Add timestamp to filename output?

### ISSUE THREAD

**Issue by Cormak** [schomery/easy-screenshot#4]
Currently, the filename is just the title and if you make multiple screenshots on the same page it tries to save the images with the same filename? Can we have an option to add a timestamp so we can get files whose names don't conflict? Perhaps with format 01-01-2000 - 0:00:00?

**Comment by schomery** [comment]
Thanks for the report. Next version will have timestamps appended to filenames.

**Comment by Cormak** [comment]
Thank you!
