### ISSUE TITLE
FR: Add a toolbar button to perform the capture

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/easy-screenshot#6]
The toolbar button could have a dropdown menu to allow selecting between entire page, viewport, and selection.

**Comment by schomery** [comment]
Currently, there is no toolbar button at all. To me, this just clutters the browser area. We have these options in the right-click menu over a page. It is pretty straightforward to add a toolbar button for this extension, but I am not sure if this is a useful addition.

**Comment by Gitoffthelawn** [comment]
I can only speak from personal experience, but I have used a toolbar button for every screenshot tool I've used.  I find it natural and intuitive, especially when using the feature frequently.

I personally find hunting down the correct menuitem in the context menu to be laborious and slower.

I don't think there is a right or wrong when it comes to this issue.  But I know, for me personally, the lack of a toolbar button prevents me from using the extension. :-(

**Comment by schomery** [comment]
Please give the latest dev version a try and let me know if there is any issue with this new implementation

![screen shot 2017-05-10 at 7 13 31 pm](https://cloud.githubusercontent.com/assets/11704051/25904587/ed4b5fa8-35b4-11e7-964b-921faf50e9f5.png)

**Comment by Gitoffthelawn** [comment]
I'll give it a try.  Thanks!  (I like the order of menuitems you used too.)

**Comment by Gitoffthelawn** [comment]
Hmmm... it looks like dev version is not on AMO yet.
