### ISSUE TITLE
addons.mozilla.org Install Button FF 57-

### ISSUE THREAD

**Issue by Francewhoa** [schomery/easy-screenshot#8]
## Challenge
About the newer version of this add-on 0.3.3 for Firefox which uses WebExtension at https://addons.mozilla.org/en-US/firefox/addon/web-clipper-easy-screenshot/

It reads "Compatible with Firefox 57+" but presently users with Firefox _older_ than 57 are able to install the extension. As a result it's risky that a large number of users will have issues.

## Suggested resolution
On that page https://addons.mozilla.org/en-US/firefox/addon/web-clipper-easy-screenshot/
I suggest to configure that page so that only users with Firefox 57+ are able to install it. The add-on maintainer is able to easily and quickly activate that feature. Assuming it works.

## Steps to reproduce issue
1. Using Firefox 45.9.0 go to https://addons.mozilla.org/en-US/firefox/addon/web-clipper-easy-screenshot/
1. Click on "Add to Firefox" button. Find [that screenshot](https://cloud.githubusercontent.com/assets/119942/26336880/ed093410-3f29-11e7-8215-766760f0b0fa.jpg) to clarify location. The expected result is that users should [not be able to click on that button](https://cloud.githubusercontent.com/assets/119942/26337037/f75b4d44-3f2a-11e7-9323-734fe209df47.jpg). That button should be gray out/deactivated.
1. After that add-on is installed. Try to use it. It will not work. Nothing works. That's normal because it requires Firefox 57+. It's risky that user will post a negative review. Which in turn affect the number of future user and contributors.

## Screenshots
![](https://cloud.githubusercontent.com/assets/119942/26336880/ed093410-3f29-11e7-8215-766760f0b0fa.jpg)
![](https://cloud.githubusercontent.com/assets/119942/26337037/f75b4d44-3f2a-11e7-9323-734fe209df47.jpg)

**Comment by schomery** [comment]
> I suggest to configure that page so that only users with Firefox 57+ are able to install it.

I think the WebEx version is only compatible with FF > 48.0. The AMO config was for FF > 42 which is now fixed.

**Comment by Francewhoa** [comment]
Good morning schomery :) Thanks. Confirming it is fixed now.
![web clipper easy screenshot webextension add-ons for firefox 2017-05-23 10-43-54 am](https://cloud.githubusercontent.com/assets/119942/26368168/a05c61ec-3fa5-11e7-8d08-771d325cc93a.png)
